FROM node:20-alpine

WORKDIR /app

RUN corepack enable

ARG NEXT_PUBLIC_LANDING_URL=http://localhost:3001
ARG NEXT_PUBLIC_PARTICLE_PROJECT_ID=
ARG NEXT_PUBLIC_PARTICLE_CLIENT_KEY=
ARG NEXT_PUBLIC_PARTICLE_APP_ID=
ARG NEXT_PUBLIC_PARTICLE_7702_CHAIN_ID=42161
ARG NEXT_PUBLIC_UNIVERSAL_ACCOUNT_VERSION=
ARG NEXT_PUBLIC_PARTICLE_REQUIRE_GAS_SPONSORSHIP=false
ARG NEXT_PUBLIC_MOM3_BACKEND_URL=http://localhost:4000
ARG NEXT_PUBLIC_MOM3_REALTIME_URL=ws://localhost:4000/realtime

ENV NEXT_PUBLIC_LANDING_URL=$NEXT_PUBLIC_LANDING_URL
ENV NEXT_PUBLIC_PARTICLE_PROJECT_ID=$NEXT_PUBLIC_PARTICLE_PROJECT_ID
ENV NEXT_PUBLIC_PARTICLE_CLIENT_KEY=$NEXT_PUBLIC_PARTICLE_CLIENT_KEY
ENV NEXT_PUBLIC_PARTICLE_APP_ID=$NEXT_PUBLIC_PARTICLE_APP_ID
ENV NEXT_PUBLIC_PARTICLE_7702_CHAIN_ID=$NEXT_PUBLIC_PARTICLE_7702_CHAIN_ID
ENV NEXT_PUBLIC_UNIVERSAL_ACCOUNT_VERSION=$NEXT_PUBLIC_UNIVERSAL_ACCOUNT_VERSION
ENV NEXT_PUBLIC_PARTICLE_REQUIRE_GAS_SPONSORSHIP=$NEXT_PUBLIC_PARTICLE_REQUIRE_GAS_SPONSORSHIP
ENV NEXT_PUBLIC_MOM3_BACKEND_URL=$NEXT_PUBLIC_MOM3_BACKEND_URL
ENV NEXT_PUBLIC_MOM3_REALTIME_URL=$NEXT_PUBLIC_MOM3_REALTIME_URL

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start", "--hostname", "0.0.0.0", "--port", "3000"]
